# Generated by Django 5.0.6 on 2024-07-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('wagtailusers', '0013_userprofile_density'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailusers.userprofile')),
                ('user_type', models.CharField(choices=[('accounts', 'Accounts'), ('store', 'Store'), ('admin', 'Admin')], default='accounts', max_length=10)),
            ],
            bases=('wagtailusers.userprofile',),
        ),
    ]
