# Generated by Django 5.0.6 on 2024-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Superadmin'), (2, 'Admin'), (3, 'Editor'), (4, 'Viewer')], default=4),
        ),
    ]
