# Generated by Django 5.0.6 on 2024-08-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatmessage_admin_remove_chatmessage_user_and_more'),
    ]

    operations = [
    ]
