# Generated by Django 5.0.6 on 2024-07-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_brand_product_cooling_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
