# Generated by Django 5.0.6 on 2024-07-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalogue',
            field=models.FileField(blank=True, null=True, upload_to='product_catalogues/'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_installation',
            field=models.BooleanField(default=False),
        ),
    ]
