# Generated by Django 5.0.6 on 2024-08-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Direct Bank Transfer'), ('cheque', 'Cheque Payment'), ('paypal', 'PayPal Payment')], default='bank_transfer', max_length=20),
        ),
    ]
